### PR TITLE
Add 'View on Cloud Console' button as CTA

### PR DESCRIPTION
**Pull request by ahmetb**
Constructed URL to send users to Cloud Console for
playing with the deployed application further.

Also added handling for when container is not running
on Cloud Run.

cc: @steren PTAL
cc: @code128 for design input

### CODE REVIEW

**Comment by ahmetb** [comment]
New preview:
image

**Comment by steren** [comment]
I am supportive of a link back to the Console, but we should not have 2 primary (blue) buttons 
The primary one should be the existing one (quickstart).
You can either use a secondary (white) button for the link to console. Or use an hyperlink in the text itself.

**Comment by ahmetb** [comment]
Changed to:
image

**Comment by steren** [comment]
Thanks. 

Maybe "View in Cloud Console" instead of "View on Cloud Console"?

**Review by steren — APPROVED** [review]

**Pull request merged**
