### PR TITLE
Add CloudBuild for CICD as demo

### PR DESCRIPTION
**Pull request by pydevops**
- Added cloudbuild.yaml
- Added the instruction to add Cloud Build Trigger for a github repo.
- Deployed it and verified in a GCP account's Cloud Run

### CODE REVIEW

**Comment by pydevops** [comment]
@googlebot I signed it!

**Comment by ahmetb** [comment]
I'm a bit hesitant about this:

- we already have an internal GCB build that might get confused by this (probably not)
- this repo is meant to be very simple and small with just the source code of the sample app (if we're not gonna use this GCB file, adding this isn't very helpful as it might break without us realizing)
- we have an official tutorial about GCB+Cloud Run in the https://cloud.google.com/run/docs, plus `awesome-cloudrun` repo links to several examples of this, as well.

**Comment by pydevops** [comment]
@ahmetb yup I agree. This should be kept simple.

**Comment by steren** [comment]
I agree with @ahmetb's points.
(the main point being that this is the demo container that we automatically build and use inside the product itself (gcr.io/cloudrun/hello), adding a `cloudbuild.yaml` might be misleading for future maintainers.)

In addition, Cloud Build is de-coupled from Cloud Run, so for a Cloud Run Hello World, you should not need a cloudbuild.yaml file.

**Pull request closed without merging**
