### PR TITLE
Use go.mod, move to go 1.14, update smaller base image

### LINKED ISSUE #30: Move to Go 1.14, use go.mod use smaller base image

### PR DESCRIPTION
**Pull request by steren**
Fix #30

### CODE REVIEW

**Comment by steren** [comment]
oops sorry ignore for now, it doesn't run

**Comment by steren** [comment]
OK, good for review now, it runs.

**Comment by ahmetb** [comment]
If my memory serves me, we intentionally kept this to use ubuntu image base, so beginners can take a look at its source code and adapt the dockerfile for other languages in their apps.

**Comment by steren** [comment]
Mmm, on the opposite: the this repo is not intended to serve as a boilerplate or hello world example.
Its single purpose is to offer the demo container. This should contain as less as possible.

**Comment by ahmetb** [comment]
For the record, switching from `alpine` to Google-based image was your call: f8d7e318d13ef40d91e6711193d911a56a78ebe9, 0ee75a7b72f0843e60a636277d8615d68bc51139. I think we discussed this over a year ago as well and I was convinced Ubuntu is there so beginners can `apt get` new things into this sample Dockerfile with less friction. I'm indifferent otherwise. :)

**Comment by steren** [comment]
Thanks for the forensic.

My motivation was not to use Ubuntu, but to use a Google managed based image, under the assumption that it would be more secure and better maintained.

But container vulnerability scans says that Ubuntu contains a lot of known vulnerabilities. I prefer to optimize for reducing that number.

Sadly, I do not see any slim base image in gcr.io/cloud-marketplace/google, so I suggest to use `alpine`? Any other suggestion?

**Pull request merged**
